pnpMode: loose

nodeLinker: pnp

packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  "@vitest/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/utils": '*'
  eslint-plugin-tailwindcss@*:
    dependencies:
      tailwindcss: '*'
  eslint-plugin-mdx@*:
    dependencies:
      "eslint-plugin-react": '*'
